name: 'Clean Directory'
description: 'Deletes all files in the target directory.'
inputs:
  target-directory:
    description: The directory to be cleaned.
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - '${{ inputs.target-directory }}'
branding:
  icon: delete
  color: red
  